version: 2
updates:
  - package-ecosystem: "pip"
    directory: "../app"        # emplacement du requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
