version: '3.7'
services:
  ctfd:
    image: ctfd/ctfd:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/ctfd.db
    volumes:
      - ./ctfd-data:/data
